import { StyleSheet } from "react-native";

import { Spacing } from "@/constants/theme";

export const styles = StyleSheet.create({
  panel: { alignSelf: "stretch", gap: Spacing.one },
  sleepActionRow: {
    flexDirection: "row",
    alignSelf: "stretch",
    gap: Spacing.one,
  },
  sleepActionMain: { flex: 1 },
  nightWakingSlot: { width: "30%" },
  nightWakingPressable: { flex: 1 },
  nightWakingButton: {
    flex: 1,
    minHeight: 54,
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.one,
    paddingHorizontal: Spacing.one,
    borderRadius: 20,
    borderWidth: 1,
    overflow: "hidden",
  },
  nightWakingLabel: {
    fontSize: 10,
    lineHeight: 12,
    fontWeight: "700",
    textAlign: "center",
  },
  eventRow: { flexDirection: "row", alignSelf: "stretch", gap: Spacing.one },
  eventNarrow: { flex: 2 },
  eventWide: { flex: 6 },
  overlay: {
    position: "absolute",
    zIndex: 10,
    elevation: 10,
    overflow: "hidden",
  },
  card: {
    flex: 1,
    padding: Spacing.four,
    gap: Spacing.two,
    borderWidth: 1,
    borderRadius: 20,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.three,
    transform: [{ translateY: -5 }],
  },
  closeButton: {
    width: 42,
    height: 42,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 21,
    borderWidth: 1,
  },
  title: { flex: 1, fontSize: 16, fontWeight: "700" },
  details: { flex: 1, minHeight: 0 },
  detailsContent: { flexGrow: 1, gap: Spacing.two },
  sleepOptions: { flex: 1, gap: Spacing.two },
  options: { flex: 1, flexDirection: "row", gap: Spacing.two },
  choice: {
    flex: 1,
    minHeight: 38,
    gap: Spacing.one,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(122, 78, 45, 0.34)",
    borderRadius: 20,
    paddingHorizontal: Spacing.two,
    backgroundColor: "rgba(255,255,255,0.56)",
  },
  choiceSelected: {
    borderWidth: 1,
    borderColor: "#7A4E2D",
    backgroundColor: "rgba(255,248,235,0.92)",
  },
  choiceSleep: {
    borderColor: "rgba(255,255,255,0.62)",
    backgroundColor: "rgba(255,255,255,0.14)",
  },
  choiceSleepSelected: {
    borderWidth: 1,
    borderColor: "#FFFFFF",
    backgroundColor: "rgba(255,255,255,0.9)",
  },
  choiceText: {
    color: "#3E2D19",
    fontSize: 12,
    fontWeight: "700",
    textAlign: "center",
  },
  step: { flexDirection: "row", gap: Spacing.two, minHeight: 48 },
  stepFill: { flex: 1 },
  breastSides: { flex: 1, gap: Spacing.two },
  breastSidesTop: { flex: 7, minHeight: 0 },
  breastSidesBottom: { flex: 3, minHeight: 0 },
  bottle: { flex: 1, gap: Spacing.two },
  bottleField: { flex: 1 },
  bottleChoiceRow: { flex: 1 },
  wheel: {
    flex: 1,
    minHeight: 48,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderRadius: 20,
  },
  wheelText: { fontSize: 15, lineHeight: 21, fontWeight: "700" },
  volume: {
    flex: 1,
    borderWidth: 1,
    borderRadius: 20,
    paddingHorizontal: Spacing.three,
    paddingVertical: Spacing.three,
    fontSize: 15,
    lineHeight: 21,
    fontWeight: "700",
    textAlign: "center",
    textAlignVertical: "center",
  },
  footer: { flexDirection: "row", gap: Spacing.two },
  back: {
    flex: 1,
    minHeight: 46,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 20,
    borderWidth: 1,
  },
  backText: { fontSize: 15, fontWeight: "700" },
  save: {
    flex: 1,
    minHeight: 46,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 20,
    borderWidth: 1,
  },
  saveDisabled: { opacity: 0.45 },
  saveText: { color: "#3E2D19", fontSize: 15, fontWeight: "700" },
  pressed: { opacity: 0.7 },
});
